"""Declarative command table: every generated CLI command in one place."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Param:
    """One CLI parameter mapped to a client-method keyword argument."""

    name: str
    kind: str = "str"  # str | int | bool | json | value | multi
    required: bool = False
    help: str = ""


@dataclass(frozen=True)
class Spec:
    """One generated CLI command bound to a client namespace method."""

    group: str
    name: str
    namespace: str
    method: str
    params: tuple[Param, ...] = ()
    help: str = ""


SPECS: tuple[Spec, ...] = (
    Spec(
        "file",
        "list",
        "files",
        "list",
        (Param("query"), Param("older_than"), Param("count", "int")),
        "List files, newest first.",
    ),
    Spec("file", "get", "files", "get", (Param("identifier", required=True),)),
    Spec("file", "delete", "files", "delete", (Param("identifier", required=True),)),
    Spec("file", "count", "files", "count", (Param("query"),)),
    Spec(
        "file",
        "request-sample",
        "files",
        "request_sample",
        (Param("identifier", required=True),),
        "Get a public download URL for a sample.",
    ),
    Spec(
        "file",
        "download-token",
        "files",
        "download_token",
        (Param("identifier", required=True),),
    ),
    Spec(
        "file",
        "download-zip-token",
        "files",
        "download_zip_token",
        (Param("identifier", required=True),),
    ),
    Spec(
        "config",
        "list",
        "configs",
        "list",
        (Param("query"), Param("older_than"), Param("count", "int")),
    ),
    Spec("config", "get", "configs", "get", (Param("identifier", required=True),)),
    Spec(
        "config", "delete", "configs", "delete", (Param("identifier", required=True),)
    ),
    Spec("config", "count", "configs", "count", (Param("query"),)),
    Spec("config", "stats", "configs", "stats", (Param("time_range"),)),
    Spec(
        "config",
        "create",
        "configs",
        "create",
        (
            Param("family", required=True),
            Param("cfg", "json", required=True),
            Param("config_type"),
            Param("parent"),
            Param("upload_as"),
            Param("tags", "multi"),
            Param("share_3rd_party", "bool"),
        ),
    ),
    Spec(
        "config",
        "put",
        "configs",
        "put",
        (Param("identifier", required=True), Param("body", "json", required=True)),
    ),
    Spec(
        "blob",
        "list",
        "blobs",
        "list",
        (Param("query"), Param("older_than"), Param("count", "int")),
    ),
    Spec("blob", "get", "blobs", "get", (Param("identifier", required=True),)),
    Spec("blob", "delete", "blobs", "delete", (Param("identifier", required=True),)),
    Spec("blob", "count", "blobs", "count", (Param("query"),)),
    Spec(
        "blob",
        "create",
        "blobs",
        "create",
        (
            Param("blob_name", required=True),
            Param("blob_type", required=True),
            Param("content", required=True),
            Param("parent"),
            Param("upload_as"),
            Param("tags", "multi"),
            Param("share_3rd_party", "bool"),
        ),
    ),
    Spec(
        "blob",
        "put",
        "blobs",
        "put",
        (Param("identifier", required=True), Param("body", "json", required=True)),
    ),
    Spec(
        "object",
        "list",
        "objects",
        "list",
        (Param("query"), Param("older_than"), Param("count", "int")),
    ),
    Spec("object", "get", "objects", "get", (Param("identifier", required=True),)),
    Spec(
        "object", "delete", "objects", "delete", (Param("identifier", required=True),)
    ),
    Spec("object", "count", "objects", "count", (Param("query"),)),
    Spec(
        "object",
        "favorite",
        "objects",
        "favorite",
        (Param("identifier", required=True),),
    ),
    Spec(
        "object",
        "unfavorite",
        "objects",
        "unfavorite",
        (Param("identifier", required=True),),
    ),
    Spec(
        "object",
        "share-3rd-party",
        "objects",
        "share_3rd_party",
        (Param("identifier", required=True),),
    ),
    Spec("tag", "list", "tags", "list", (Param("query"), Param("count", "int"))),
    Spec(
        "tag",
        "get",
        "tags",
        "get",
        (Param("identifier", required=True), Param("object_type")),
    ),
    Spec(
        "tag",
        "add",
        "tags",
        "add",
        (
            Param("identifier", required=True),
            Param("tag", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "tag",
        "remove",
        "tags",
        "remove",
        (
            Param("identifier", required=True),
            Param("tag", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "comment",
        "list",
        "comments",
        "list",
        (Param("identifier", required=True), Param("object_type")),
    ),
    Spec(
        "comment",
        "add",
        "comments",
        "add",
        (
            Param("identifier", required=True),
            Param("comment", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "comment",
        "remove",
        "comments",
        "remove",
        (
            Param("identifier", required=True),
            Param("comment_id", "int", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "attribute",
        "list",
        "attributes",
        "list",
        (
            Param("identifier", required=True),
            Param("object_type"),
            Param("hidden", "bool"),
        ),
    ),
    Spec(
        "attribute",
        "add",
        "attributes",
        "add",
        (
            Param("identifier", required=True),
            Param("key", required=True),
            Param("value", "value", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "attribute",
        "remove",
        "attributes",
        "remove",
        (
            Param("identifier", required=True),
            Param("attribute_id", "int", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "attribute",
        "legacy-get",
        "attributes",
        "legacy_get",
        (
            Param("identifier", required=True),
            Param("object_type"),
            Param("hidden", "bool"),
        ),
    ),
    Spec(
        "attribute",
        "legacy-add",
        "attributes",
        "legacy_add",
        (
            Param("identifier", required=True),
            Param("key", required=True),
            Param("value", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "attribute",
        "legacy-remove",
        "attributes",
        "legacy_remove",
        (
            Param("identifier", required=True),
            Param("key", required=True),
            Param("value"),
            Param("object_type"),
        ),
    ),
    Spec("share", "groups", "shares", "groups"),
    Spec(
        "share",
        "get",
        "shares",
        "get",
        (Param("identifier", required=True), Param("object_type")),
    ),
    Spec(
        "share",
        "set",
        "shares",
        "share",
        (
            Param("identifier", required=True),
            Param("group", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "relation",
        "get",
        "relations",
        "get",
        (Param("identifier", required=True), Param("object_type")),
    ),
    Spec(
        "relation",
        "link",
        "relations",
        "link",
        (
            Param("parent", required=True),
            Param("child", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "relation",
        "unlink",
        "relations",
        "unlink",
        (
            Param("parent", required=True),
            Param("child", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "karton",
        "list",
        "karton",
        "list",
        (
            Param("identifier", required=True),
            Param("object_type"),
            Param("older_than"),
        ),
    ),
    Spec(
        "karton",
        "get",
        "karton",
        "get",
        (
            Param("identifier", required=True),
            Param("analysis_id", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "karton",
        "resubmit",
        "karton",
        "resubmit",
        (
            Param("identifier", required=True),
            Param("object_type"),
            Param("arguments", "json"),
        ),
    ),
    Spec(
        "karton",
        "assign",
        "karton",
        "assign",
        (
            Param("identifier", required=True),
            Param("analysis_id", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "karton",
        "remove",
        "karton",
        "remove",
        (
            Param("identifier", required=True),
            Param("analysis_id", required=True),
            Param("object_type"),
        ),
    ),
    Spec("quick-query", "list", "quick_queries", "list", (Param("object_type"),)),
    Spec(
        "quick-query",
        "create",
        "quick_queries",
        "create",
        (
            Param("name", required=True),
            Param("query", required=True),
            Param("object_type"),
        ),
    ),
    Spec(
        "quick-query",
        "remove",
        "quick_queries",
        "remove",
        (Param("query_id", "int", required=True),),
    ),
    Spec(
        "auth",
        "login",
        "auth",
        "login",
        (Param("login", required=True), Param("password", required=True)),
    ),
    Spec("auth", "refresh", "auth", "refresh"),
    Spec("auth", "validate", "auth", "validate"),
    Spec("auth", "groups", "auth", "groups"),
    Spec(
        "auth",
        "register",
        "auth",
        "register",
        (
            Param("login", required=True),
            Param("email", required=True),
            Param("additional_info", required=True),
            Param("recaptcha"),
        ),
    ),
    Spec(
        "auth",
        "change-password",
        "auth",
        "change_password",
        (Param("password", required=True), Param("token", required=True)),
    ),
    Spec(
        "auth",
        "recover-password",
        "auth",
        "recover_password",
        (
            Param("login", required=True),
            Param("email", required=True),
            Param("recaptcha"),
        ),
    ),
    Spec(
        "auth",
        "request-password-change",
        "auth",
        "request_password_change",
    ),
    Spec("user", "list", "users", "list", (Param("pending", "bool"),)),
    Spec("user", "get", "users", "get", (Param("login", required=True),)),
    Spec(
        "user",
        "create",
        "users",
        "create",
        (
            Param("login", required=True),
            Param("email", required=True),
            Param("additional_info", required=True),
            Param("feed_quality"),
            Param("send_email", "bool"),
        ),
    ),
    Spec(
        "user",
        "update",
        "users",
        "update",
        (
            Param("login", required=True),
            Param("email"),
            Param("additional_info"),
            Param("feed_quality"),
            Param("disabled", "bool"),
            Param("send_email", "bool"),
        ),
    ),
    Spec("user", "delete", "users", "delete", (Param("login", required=True),)),
    Spec(
        "user",
        "pending-accept",
        "users",
        "pending_accept",
        (Param("login", required=True),),
    ),
    Spec(
        "user",
        "pending-reject",
        "users",
        "pending_reject",
        (Param("login", required=True),),
    ),
    Spec(
        "user",
        "change-password-token",
        "users",
        "change_password_token",
        (Param("login", required=True),),
    ),
    Spec(
        "user",
        "request-password-change",
        "users",
        "request_password_change",
        (Param("login", required=True),),
    ),
    Spec("user", "profile", "users", "profile", (Param("login", required=True),)),
    Spec(
        "api-key",
        "create",
        "api_keys",
        "create",
        (Param("login", required=True), Param("name", required=True)),
    ),
    Spec(
        "api-key",
        "delete",
        "api_keys",
        "delete",
        (Param("api_key_id", required=True),),
    ),
    Spec("group", "list", "groups", "list"),
    Spec("group", "get", "groups", "get", (Param("name", required=True),)),
    Spec(
        "group",
        "create",
        "groups",
        "create",
        (Param("name", required=True), Param("capabilities", "multi")),
    ),
    Spec(
        "group",
        "update",
        "groups",
        "update",
        (
            Param("name", required=True),
            Param("new_name"),
            Param("capabilities", "multi"),
            Param("default", "bool"),
            Param("provider"),
            Param("workspace", "bool"),
        ),
    ),
    Spec("group", "delete", "groups", "delete", (Param("name", required=True),)),
    Spec(
        "group",
        "member-add",
        "groups",
        "member_add",
        (Param("name", required=True), Param("login", required=True)),
    ),
    Spec(
        "group",
        "member-update",
        "groups",
        "member_update",
        (
            Param("name", required=True),
            Param("login", required=True),
            Param("group_admin", "bool"),
        ),
    ),
    Spec(
        "group",
        "member-delete",
        "groups",
        "member_delete",
        (Param("name", required=True), Param("login", required=True)),
    ),
    Spec("attribute-def", "list", "attribute_defs", "list", (Param("access"),)),
    Spec(
        "attribute-def",
        "get",
        "attribute_defs",
        "get",
        (Param("key", required=True),),
    ),
    Spec(
        "attribute-def",
        "create",
        "attribute_defs",
        "create",
        (
            Param("key", required=True),
            Param("label", required=True),
            Param("description", required=True),
            Param("hidden", "bool"),
            Param("url_template"),
            Param("rich_template"),
            Param("example_value"),
        ),
    ),
    Spec(
        "attribute-def",
        "update",
        "attribute_defs",
        "update",
        (
            Param("key", required=True),
            Param("label"),
            Param("description"),
            Param("hidden", "bool"),
            Param("url_template"),
            Param("rich_template"),
            Param("example_value"),
        ),
    ),
    Spec(
        "attribute-def",
        "delete",
        "attribute_defs",
        "delete",
        (Param("key", required=True),),
    ),
    Spec(
        "attribute-def",
        "permissions",
        "attribute_defs",
        "permissions",
        (Param("key", required=True),),
    ),
    Spec(
        "attribute-def",
        "permission-set",
        "attribute_defs",
        "permission_set",
        (
            Param("key", required=True),
            Param("group_name", required=True),
            Param("can_read", "bool"),
            Param("can_set", "bool"),
        ),
    ),
    Spec(
        "attribute-def",
        "permission-delete",
        "attribute_defs",
        "permission_delete",
        (Param("key", required=True), Param("group_name", required=True)),
    ),
    Spec(
        "metakey",
        "list-keys",
        "metakeys",
        "list_keys",
        (Param("access", required=True),),
    ),
    Spec("metakey", "definitions", "metakeys", "definitions"),
    Spec("metakey", "get", "metakeys", "get", (Param("key", required=True),)),
    Spec(
        "metakey",
        "create",
        "metakeys",
        "create",
        (
            Param("key", required=True),
            Param("label", required=True),
            Param("description", required=True),
            Param("template", required=True),
            Param("hidden", "bool"),
        ),
    ),
    Spec(
        "metakey",
        "update",
        "metakeys",
        "update",
        (
            Param("key", required=True),
            Param("label"),
            Param("description"),
            Param("template"),
            Param("hidden", "bool"),
        ),
    ),
    Spec("metakey", "delete", "metakeys", "delete", (Param("key", required=True),)),
    Spec(
        "metakey",
        "permission-set",
        "metakeys",
        "permission_set",
        (
            Param("key", required=True),
            Param("group_name", required=True),
            Param("can_read", "bool"),
            Param("can_set", "bool"),
        ),
    ),
    Spec(
        "metakey",
        "permission-delete",
        "metakeys",
        "permission_delete",
        (Param("key", required=True), Param("group_name", required=True)),
    ),
    Spec("oauth", "providers", "oauth", "providers"),
    Spec("oauth", "identities", "oauth", "identities"),
    Spec(
        "oauth",
        "register",
        "oauth",
        "register_provider",
        (Param("config", "json", required=True),),
    ),
    Spec("oauth", "get", "oauth", "get", (Param("provider_name", required=True),)),
    Spec(
        "oauth",
        "update",
        "oauth",
        "update",
        (
            Param("provider_name", required=True),
            Param("config", "json", required=True),
        ),
    ),
    Spec(
        "oauth", "delete", "oauth", "delete", (Param("provider_name", required=True),)
    ),
    Spec(
        "oauth",
        "authenticate",
        "oauth",
        "authenticate",
        (Param("provider_name", required=True), Param("payload", "json")),
    ),
    Spec(
        "oauth",
        "bind",
        "oauth",
        "bind_account",
        (
            Param("provider_name", required=True),
            Param("code", required=True),
            Param("nonce", required=True),
            Param("state", required=True),
        ),
    ),
    Spec(
        "oauth", "logout", "oauth", "logout", (Param("provider_name", required=True),)
    ),
    Spec("remote", "list", "remotes", "list"),
    Spec(
        "remote",
        "pull-file",
        "remotes",
        "pull_file",
        (Param("remote_name", required=True), Param("identifier", required=True)),
    ),
    Spec(
        "remote",
        "pull-config",
        "remotes",
        "pull_config",
        (Param("remote_name", required=True), Param("identifier", required=True)),
    ),
    Spec(
        "remote",
        "pull-blob",
        "remotes",
        "pull_blob",
        (Param("remote_name", required=True), Param("identifier", required=True)),
    ),
    Spec(
        "remote",
        "push-file",
        "remotes",
        "push_file",
        (Param("remote_name", required=True), Param("identifier", required=True)),
    ),
    Spec(
        "remote",
        "push-config",
        "remotes",
        "push_config",
        (Param("remote_name", required=True), Param("identifier", required=True)),
    ),
    Spec(
        "remote",
        "push-blob",
        "remotes",
        "push_blob",
        (Param("remote_name", required=True), Param("identifier", required=True)),
    ),
    Spec("server", "ping", "server", "ping"),
    Spec("server", "info", "server", "info"),
    Spec("server", "admin", "server", "admin_info"),
    Spec("server", "docs", "server", "docs"),
    Spec("server", "metrics", "server", "metrics"),
)

GROUP_HELP = {
    "file": "File objects: list, inspect, upload, download.",
    "config": "Malware configuration objects.",
    "blob": "Text blob objects.",
    "object": "Generic object operations.",
    "tag": "Tags on objects.",
    "comment": "Comments on objects.",
    "attribute": "Object attributes (and legacy metakeys).",
    "share": "Object sharing.",
    "relation": "Parent/child relations between objects.",
    "karton": "Karton analyses.",
    "quick-query": "Stored quick queries.",
    "auth": "Authentication and account flows.",
    "user": "User administration.",
    "api-key": "API key management.",
    "group": "Group administration.",
    "attribute-def": "Attribute key definitions.",
    "metakey": "Legacy metakey definitions.",
    "oauth": "OpenID Connect providers and identities.",
    "remote": "Remote MWDB instances (pull/push).",
    "server": "Server status and metadata.",
}
